info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T08:10:26.602Z"}
info: Connected to the database. {"timestamp":"2022-07-18T08:10:29.336Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T10:54:18.756Z"}
info: Connected to the database. {"timestamp":"2022-07-18T10:54:18.806Z"}
error: 
    status - 500 
    message - ValidationError: "lastName" length must be at least 4 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-18T10:57:25.296Z"}
error: 
    status - 500 
    message - ValidationError: "email" is not allowed 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-18T10:57:41.052Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T11:00:58.356Z"}
info: Connected to the database. {"timestamp":"2022-07-18T11:00:58.399Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T11:15:39.504Z"}
info: Connected to the database. {"timestamp":"2022-07-18T11:15:39.548Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T11:22:05.942Z"}
info: Connected to the database. {"timestamp":"2022-07-18T11:22:05.983Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/62d53d6f5cd160275055626a 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-18T11:22:49.770Z"}
error: 
    status - 500 
    message - TypeError: UserService.newUser is not a function
    at _callee3$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/user.controller.js:50:36)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (C:\CFP_170\NodeJs\FundooNotes\src\validators\/user.validator.js:15:5)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-18T11:24:31.897Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T11:25:51.113Z"}
info: Connected to the database. {"timestamp":"2022-07-18T11:25:51.149Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T16:36:42.840Z"}
info: Connected to the database. {"timestamp":"2022-07-18T16:36:42.889Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-18T16:39:16.593Z"}
info: Connected to the database. {"timestamp":"2022-07-18T16:39:16.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-19T03:09:25.967Z"}
info: Connected to the database. {"timestamp":"2022-07-19T03:09:26.023Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).email.required is not a function
    at newUserValidator (C:\CFP_170\NodeJs\FundooNotes\src\validators\/user.validator.js:7:31)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:328:13)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-19T03:11:20.571Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-19T03:12:33.700Z"}
info: Connected to the database. {"timestamp":"2022-07-19T03:12:33.766Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-19T03:12:42.614Z"}
error: 
    status - 500 
    message - Error: User dosen't exist
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\services\/user.service.js:9:11)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-19T03:13:43.766Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-19T03:15:55.698Z"}
info: Connected to the database. {"timestamp":"2022-07-19T03:15:55.757Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" must be a string 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-19T03:17:29.780Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-19T03:18:57.410Z"}
info: Connected to the database. {"timestamp":"2022-07-19T03:18:57.512Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (C:\CFP_170\NodeJs\FundooNotes\src\validators\/user.validator.js:12:16)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:328:13)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-19T03:19:02.546Z"}
<<<<<<< HEAD
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T13:24:46.090Z"}
info: Connected to the database. {"timestamp":"2022-07-20T13:24:46.128Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'addNote')
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:15:40)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at addNote (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:12:21)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/notes 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-20T13:28:11.539Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T13:53:14.448Z"}
info: Connected to the database. {"timestamp":"2022-07-20T13:53:14.508Z"}
error: uncaughtException: this.any is not a function
TypeError: this.any is not a function
    at model.root.<computed> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@hapi\joi\lib\index.js:67:25)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2305:62
    at Array.forEach (<anonymous>)
    at _evaluateRequiredFunctions (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2301:51)
    at _getPathsToValidate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2317:3)
    at model.Document.$__validate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2491:23)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {"date":"Wed Jul 20 2022 19:25:42 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":42169},"process":{"argv":["node","C:\\CFP_170\\NodeJs\\FundooNotes\\src\\index.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18430292,"external":20099289,"heapTotal":48517120,"heapUsed":44114480,"rss":80375808},"pid":17364,"uid":null,"version":"v16.15.1"},"stack":"TypeError: this.any is not a function\n    at model.root.<computed> (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js:67:25)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2305:62\n    at Array.forEach (<anonymous>)\n    at _evaluateRequiredFunctions (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2301:51)\n    at _getPathsToValidate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2317:3)\n    at model.Document.$__validate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2491:23)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js:370:33\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-07-20T13:55:42.735Z","trace":[{"column":25,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js","function":"model.root.<computed>","line":67,"method":"<computed>","native":false},{"column":62,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2305,"method":null,"native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":51,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_evaluateRequiredFunctions","line":2301,"method":null,"native":false},{"column":3,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_getPathsToValidate","line":2317,"method":null,"native":false},{"column":23,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.$__validate","line":2491,"method":"$__validate","native":false},{"column":33,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js","function":null,"line":370,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":78,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T13:57:43.767Z"}
info: Connected to the database. {"timestamp":"2022-07-20T13:57:43.819Z"}
error: uncaughtException: this.any is not a function
TypeError: this.any is not a function
    at model.root.<computed> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@hapi\joi\lib\index.js:67:25)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2305:62
    at Array.forEach (<anonymous>)
    at _evaluateRequiredFunctions (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2301:51)
    at _getPathsToValidate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2317:3)
    at model.Document.$__validate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2491:23)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {"date":"Wed Jul 20 2022 19:27:52 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":42299},"process":{"argv":["node","C:\\CFP_170\\NodeJs\\FundooNotes\\src\\index.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19815755,"external":22903810,"heapTotal":82993152,"heapUsed":55544976,"rss":116867072},"pid":15056,"uid":null,"version":"v16.15.1"},"stack":"TypeError: this.any is not a function\n    at model.root.<computed> (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js:67:25)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2305:62\n    at Array.forEach (<anonymous>)\n    at _evaluateRequiredFunctions (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2301:51)\n    at _getPathsToValidate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2317:3)\n    at model.Document.$__validate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2491:23)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js:370:33\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-07-20T13:57:52.729Z","trace":[{"column":25,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js","function":"model.root.<computed>","line":67,"method":"<computed>","native":false},{"column":62,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2305,"method":null,"native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":51,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_evaluateRequiredFunctions","line":2301,"method":null,"native":false},{"column":3,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_getPathsToValidate","line":2317,"method":null,"native":false},{"column":23,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.$__validate","line":2491,"method":"$__validate","native":false},{"column":33,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js","function":null,"line":370,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":78,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T14:09:26.598Z"}
info: Connected to the database. {"timestamp":"2022-07-20T14:09:26.661Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T14:21:51.463Z"}
info: Connected to the database. {"timestamp":"2022-07-20T14:21:51.510Z"}
error: uncaughtException: this.any is not a function
TypeError: this.any is not a function
    at model.root.<computed> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@hapi\joi\lib\index.js:67:25)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2305:62
    at Array.forEach (<anonymous>)
    at _evaluateRequiredFunctions (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2301:51)
    at _getPathsToValidate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2317:3)
    at model.Document.$__validate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2491:23)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {"date":"Wed Jul 20 2022 19:52:41 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":43788},"process":{"argv":["node","C:\\CFP_170\\NodeJs\\FundooNotes\\src\\index.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18285713,"external":20084827,"heapTotal":49041408,"heapUsed":44261336,"rss":81031168},"pid":19264,"uid":null,"version":"v16.15.1"},"stack":"TypeError: this.any is not a function\n    at model.root.<computed> (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js:67:25)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2305:62\n    at Array.forEach (<anonymous>)\n    at _evaluateRequiredFunctions (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2301:51)\n    at _getPathsToValidate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2317:3)\n    at model.Document.$__validate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2491:23)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js:370:33\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-07-20T14:22:41.954Z","trace":[{"column":25,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js","function":"model.root.<computed>","line":67,"method":"<computed>","native":false},{"column":62,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2305,"method":null,"native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":51,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_evaluateRequiredFunctions","line":2301,"method":null,"native":false},{"column":3,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_getPathsToValidate","line":2317,"method":null,"native":false},{"column":23,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.$__validate","line":2491,"method":"$__validate","native":false},{"column":33,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js","function":null,"line":370,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":78,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T14:26:13.644Z"}
info: Connected to the database. {"timestamp":"2022-07-20T14:26:13.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T17:08:35.801Z"}
info: Connected to the database. {"timestamp":"2022-07-20T17:08:35.877Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T17:11:44.837Z"}
info: Connected to the database. {"timestamp":"2022-07-20T17:11:44.933Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T17:15:45.617Z"}
info: Connected to the database. {"timestamp":"2022-07-20T17:15:45.678Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T17:28:41.213Z"}
info: Connected to the database. {"timestamp":"2022-07-20T17:28:41.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-20T17:31:37.307Z"}
info: Connected to the database. {"timestamp":"2022-07-20T17:31:37.373Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T01:47:55.376Z"}
info: Connected to the database. {"timestamp":"2022-07-21T01:47:55.436Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T02:10:45.567Z"}
info: Connected to the database. {"timestamp":"2022-07-21T02:10:45.607Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T02:20:33.367Z"}
info: Connected to the database. {"timestamp":"2022-07-21T02:20:33.412Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:31:58)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:30:24)
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:94:23)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/delete/ 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-07-21T02:21:30.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T02:39:21.263Z"}
info: Connected to the database. {"timestamp":"2022-07-21T02:39:21.471Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T03:11:17.525Z"}
info: Connected to the database. {"timestamp":"2022-07-21T03:11:17.577Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-21T03:11:44.999Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T03:21:57.023Z"}
info: Connected to the database. {"timestamp":"2022-07-21T03:21:57.088Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T03:23:04.925Z"}
info: Connected to the database. {"timestamp":"2022-07-21T03:23:05.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T03:27:37.109Z"}
info: Connected to the database. {"timestamp":"2022-07-21T03:27:37.221Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T03:36:11.022Z"}
info: Connected to the database. {"timestamp":"2022-07-21T03:36:11.084Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T07:09:45.902Z"}
info: Connected to the database. {"timestamp":"2022-07-21T07:09:45.951Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T07:12:57.172Z"}
info: Connected to the database. {"timestamp":"2022-07-21T07:12:57.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T07:35:25.663Z"}
info: Connected to the database. {"timestamp":"2022-07-21T07:35:25.712Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T07:39:31.966Z"}
info: Connected to the database. {"timestamp":"2022-07-21T07:39:32.006Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T07:42:12.165Z"}
info: Connected to the database. {"timestamp":"2022-07-21T07:42:12.208Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T08:29:02.203Z"}
info: Connected to the database. {"timestamp":"2022-07-21T08:29:02.290Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:21:10.293Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:21:10.334Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:29:39.297Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:29:39.342Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:30:57.324Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:30:57.372Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/62d8c80e1306f13f149e2b21 
      method - DELETE 
      IP - ::1
     {"timestamp":"2022-07-21T09:31:34.632Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/62d8108b497d123f58b687c1 
      method - DELETE 
      IP - ::1
     {"timestamp":"2022-07-21T09:32:51.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:37:46.451Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:37:46.503Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:40:18.547Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:40:18.600Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:41:16.452Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:41:16.492Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:47:26.683Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:47:26.743Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:49:19.548Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:49:19.611Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:50:58.677Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:50:58.719Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T09:56:06.274Z"}
info: Connected to the database. {"timestamp":"2022-07-21T09:56:06.327Z"}
error: 
    status - 500 
    message - TypeError: noteService.archieveNote is not a function
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:96:38)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at archieveNote (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:94:27)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:28:5)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/notes/62d8c80e1306f13f149e2b21/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-21T09:56:56.644Z"}
error: 
    status - 500 
    message - TypeError: noteService.archieveNote is not a function
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:96:38)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at archieveNote (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:94:27)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:28:5)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/notes/62d8c80e1306f13f149e2b21/isarchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-21T09:59:06.542Z"}
error: 
    status - 500 
    message - TypeError: noteService.archieveNote is not a function
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:96:38)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at archieveNote (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:94:27)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:28:5)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/notes/62d8c80e1306f13f149e2b21/isarchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-21T09:59:44.481Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:02:17.006Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:02:17.062Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:31:54)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archieveNote (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:30:26)
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:96:38)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/62d8c80e1306f13f149e2b21/isarchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-21T10:02:22.621Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:03:12.956Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:03:13.010Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:31:67)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archieveNote (C:\CFP_170\NodeJs\FundooNotes\src\services\/note.service.js:30:26)
    at _callee5$ (C:\CFP_170\NodeJs\FundooNotes\src\controllers\/note.controller.js:96:38)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/62d8c80e1306f13f149e2b21/isarchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-21T10:03:16.737Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:04:00.401Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:04:00.478Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:09:07.608Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:09:07.674Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:21:59.632Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:21:59.682Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:47:53.665Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:47:53.712Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:48:49.353Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:48:49.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T10:49:48.978Z"}
info: Connected to the database. {"timestamp":"2022-07-21T10:49:49.068Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T12:20:50.776Z"}
info: Connected to the database. {"timestamp":"2022-07-21T12:20:50.818Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T16:43:05.757Z"}
info: Connected to the database. {"timestamp":"2022-07-21T16:43:05.796Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T16:58:17.135Z"}
info: Connected to the database. {"timestamp":"2022-07-21T16:58:17.175Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T17:02:04.994Z"}
info: Connected to the database. {"timestamp":"2022-07-21T17:02:05.033Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T17:02:43.254Z"}
info: Connected to the database. {"timestamp":"2022-07-21T17:02:43.286Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T17:06:54.662Z"}
info: Connected to the database. {"timestamp":"2022-07-21T17:06:54.694Z"}
error: uncaughtException: this.any is not a function
TypeError: this.any is not a function
    at model.root.<computed> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@hapi\joi\lib\index.js:67:25)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2305:62
    at Array.forEach (<anonymous>)
    at _evaluateRequiredFunctions (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2301:51)
    at _getPathsToValidate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2317:3)
    at model.Document.$__validate (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\document.js:2491:23)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {"date":"Thu Jul 21 2022 23:15:12 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":142337},"process":{"argv":["node","C:\\CFP_170\\NodeJs\\FundooNotes\\src\\index.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18440367,"external":20225344,"heapTotal":49565696,"heapUsed":45359368,"rss":82014208},"pid":20240,"uid":null,"version":"v16.15.1"},"stack":"TypeError: this.any is not a function\n    at model.root.<computed> (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js:67:25)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2305:62\n    at Array.forEach (<anonymous>)\n    at _evaluateRequiredFunctions (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2301:51)\n    at _getPathsToValidate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2317:3)\n    at model.Document.$__validate (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js:2491:23)\n    at C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js:370:33\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-07-21T17:45:12.648Z","trace":[{"column":25,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@hapi\\joi\\lib\\index.js","function":"model.root.<computed>","line":67,"method":"<computed>","native":false},{"column":62,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2305,"method":null,"native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":51,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_evaluateRequiredFunctions","line":2301,"method":null,"native":false},{"column":3,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"_getPathsToValidate","line":2317,"method":null,"native":false},{"column":23,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.$__validate","line":2491,"method":"$__validate","native":false},{"column":33,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\kareem\\index.js","function":null,"line":370,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":78,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T17:46:59.072Z"}
info: Connected to the database. {"timestamp":"2022-07-21T17:46:59.125Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-21T17:49:37.217Z"}
info: Connected to the database. {"timestamp":"2022-07-21T17:49:37.256Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-21T17:49:57.214Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-22T02:36:24.589Z"}
info: Connected to the database. {"timestamp":"2022-07-22T02:36:24.804Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-22T02:38:23.947Z"}
info: Connected to the database. {"timestamp":"2022-07-22T02:38:24.069Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-23T11:09:42.350Z"}
info: Connected to the database. {"timestamp":"2022-07-23T11:09:42.414Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T13:53:42.726Z"}
info: Connected to the database. {"timestamp":"2022-07-25T13:53:42.819Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T13:56:55.599Z"}
info: Connected to the database. {"timestamp":"2022-07-25T13:56:55.693Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:18:20.109Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:18:20.156Z"}
=======
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:07:15.546Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:07:15.584Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:31:55.422Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:31:55.467Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:34:00.040Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:34:00.081Z"}
>>>>>>> UserRegistrationAndLogin
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:94:10)
<<<<<<< HEAD
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:52:28)
=======
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:43:30)
>>>>>>> UserRegistrationAndLogin
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
<<<<<<< HEAD
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:24)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5laGF5YXk0ODdAYWx0cGFuby5jb20iLCJfaWQiOiI2MmRlYTJiNjRlZWQwYzJhYjg0MzZhYzMiLCJpYXQiOjE2NTg3NTc4NTd9.mhHmRkwozofCw8x1p_2NY7AR0FzdbAB-jgsMGxD2-fc 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-25T14:19:26.011Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:21:35.603Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:21:35.657Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:25:05.925Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:25:06.006Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:27:07.260Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:27:07.311Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:28:15.419Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:28:15.571Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:32:05.699Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:32:05.746Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:34:53.288Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:34:53.347Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T14:36:04.284Z"}
info: Connected to the database. {"timestamp":"2022-07-25T14:36:04.339Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T15:22:06.516Z"}
info: Connected to the database. {"timestamp":"2022-07-25T15:22:06.577Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-25T16:53:49.179Z"}
info: Connected to the database. {"timestamp":"2022-07-25T16:53:49.277Z"}
=======
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:33:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubWNlaHNuQGdtYWlsLmNvbSIsIl9pZCI6IjYyZGY1NGExYWIzN2EzMzcyODkyNGZjNSIsImlhdCI6MTY1ODgyMDg0NX0.ldDtRxvQ-CZEqJM8ZEeLwE6DY71mujctQ9RNMQgmOWc 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-26T07:34:57.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:37:06.666Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:37:06.696Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:42:22.560Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:42:22.622Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T07:44:17.465Z"}
info: Connected to the database. {"timestamp":"2022-07-26T07:44:17.508Z"}
error: uncaughtException: noteRoute is not defined
ReferenceError: noteRoute is not defined
    at routes (C:\CFP_170\NodeJs\FundooNotes\src\routes\/index.js:15:24)
    at Object.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\src\/index.js:32:32)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (C:\CFP_170\NodeJs\FundooNotes\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (C:\CFP_170\NodeJs\FundooNotes\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\node\lib\_babel-node.js:176:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {"date":"Tue Jul 26 2022 13:19:04 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":155519},"process":{"argv":["node","C:\\CFP_170\\NodeJs\\FundooNotes\\src\\index.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19014340,"external":51718449,"heapTotal":116105216,"heapUsed":89911264,"rss":150736896},"pid":5296,"uid":null,"version":"v16.15.1"},"stack":"ReferenceError: noteRoute is not defined\n    at routes (C:\\CFP_170\\NodeJs\\FundooNotes\\src\\routes\\/index.js:15:24)\n    at Object.<anonymous> (C:\\CFP_170\\NodeJs\\FundooNotes\\src\\/index.js:32:32)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Module._compile (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Object.newLoader [as .js] (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)\n    at Object.<anonymous> (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@babel\\node\\lib\\_babel-node.js:176:21)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)\n    at node:internal/main/run_main_module:17:47","timestamp":"2022-07-26T07:49:04.493Z","trace":[{"column":24,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\src\\routes\\/index.js","function":"routes","line":15,"method":null,"native":false},{"column":32,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1105,"method":"_compile","native":false},{"column":24,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1159,"method":".js","native":false},{"column":7,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":981,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":822,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":77,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":21,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\@babel\\node\\lib\\_babel-node.js","function":null,"line":176,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1105,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1159,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":981,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":822,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":77,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":17,"method":null,"native":false}]}
<<<<<<< HEAD
>>>>>>> UserRegistrationAndLogin
=======
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T11:44:07.842Z"}
info: Connected to the database. {"timestamp":"2022-07-26T11:44:07.904Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T11:48:04.293Z"}
info: Connected to the database. {"timestamp":"2022-07-26T11:48:04.331Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T11:48:17.539Z"}
info: Connected to the database. {"timestamp":"2022-07-26T11:48:17.585Z"}
>>>>>>> UserRegistrationAndLogin
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T13:50:11.033Z"}
info: Connected to the database. {"timestamp":"2022-07-26T13:50:11.085Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T14:09:51.752Z"}
info: Connected to the database. {"timestamp":"2022-07-26T14:09:51.794Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T14:19:29.193Z"}
info: Connected to the database. {"timestamp":"2022-07-26T14:19:29.231Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T14:35:46.497Z"}
info: Connected to the database. {"timestamp":"2022-07-26T14:35:46.570Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T17:22:04.836Z"}
info: Connected to the database. {"timestamp":"2022-07-26T17:22:04.880Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T17:53:31.409Z"}
info: Connected to the database. {"timestamp":"2022-07-26T17:53:31.446Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T18:00:40.384Z"}
info: Connected to the database. {"timestamp":"2022-07-26T18:00:40.428Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-26T18:02:16.208Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-26T18:05:33.609Z"}
info: Connected to the database. {"timestamp":"2022-07-26T18:05:33.660Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-26T18:06:40.209Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:05:19.211Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:05:19.270Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:06:33.714Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:09:31.969Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:09:32.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:09:52.095Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:09:52.124Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:10:42.282Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:38:55.327Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:38:55.443Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee2$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:51:30)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at resetAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:41:23)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-27T02:39:42.196Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T02:43:09.746Z"}
info: Connected to the database. {"timestamp":"2022-07-27T02:43:09.811Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T07:46:50.214Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T07:50:45.985Z"}
info: Connected to the database. {"timestamp":"2022-07-27T07:50:46.036Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T07:51:20.143Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T08:10:00.745Z"}
info: Connected to the database. {"timestamp":"2022-07-27T08:10:00.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T10:38:13.695Z"}
info: Connected to the database. {"timestamp":"2022-07-27T10:38:13.745Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-27T11:47:40.336Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:49:56.314Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:50:41.931Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:50:41.981Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:50:49.347Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:50:57.635Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:51:23.220Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:53:56.212Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:53:56.242Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:54:03.839Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/ 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T11:54:20.207Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T11:59:25.148Z"}
info: Connected to the database. {"timestamp":"2022-07-27T11:59:25.201Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T12:03:16.144Z"}
info: Connected to the database. {"timestamp":"2022-07-27T12:03:16.184Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/%7B_id%7D 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T12:24:16.366Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:24:28)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T12:25:08.242Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/%7B_id%7D 
      method - GET 
      IP - ::1
     {"timestamp":"2022-07-27T12:42:14.788Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\CFP_170\NodeJs\FundooNotes\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:24:28)
    at tryCatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\CFP_170\NodeJs\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\CFP_170\NodeJs\FundooNotes\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T12:43:03.049Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T15:55:40.292Z"}
info: Connected to the database. {"timestamp":"2022-07-27T15:55:40.330Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'manu@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T16:24:38.175Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T16:52:35.096Z"}
info: Connected to the database. {"timestamp":"2022-07-27T16:52:35.154Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T16:57:17.244Z"}
info: Connected to the database. {"timestamp":"2022-07-27T16:57:17.297Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:00:10.245Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:00:10.291Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:44:59.606Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:44:59.644Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'manu@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T17:46:08.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-27T17:47:30.223Z"}
info: Connected to the database. {"timestamp":"2022-07-27T17:47:30.261Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'pujith008@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-27T17:48:42.802Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T02:27:46.342Z"}
info: Connected to the database. {"timestamp":"2022-07-28T02:27:46.392Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '{_id}', UserId: 'pujith008@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\CFP_170\NodeJs\FundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/%7B_id%7D 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-28T02:28:46.420Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T05:30:58.827Z"}
info: Connected to the database. {"timestamp":"2022-07-28T05:30:58.877Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T07:09:21.966Z"}
error: uncaughtException: expected 404 to equal 200
AssertionError: expected 404 to equal 200
    at Test.<anonymous> (C:\CFP_170\NodeJs\FundooNotes\tests\integration\/user.test.js:34:40)
    at Test.assert (C:\CFP_170\NodeJs\FundooNotes\node_modules\supertest\lib\test.js:181:6)
    at Server.localAssert (C:\CFP_170\NodeJs\FundooNotes\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:641:28)
    at Server.emit (node:events:527:28)
    at emitCloseNT (node:net:1728:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {"date":"Thu Jul 28 2022 12:39:22 GMT+0530 (India Standard Time)","error":{"actual":404,"expected":200,"message":"expected 404 to equal 200","name":"AssertionError","operator":"strictEqual","showDiff":true,"stack":"AssertionError: expected 404 to equal 200\n    at Test.<anonymous> (C:\\CFP_170\\NodeJs\\FundooNotes\\tests\\integration\\/user.test.js:34:40)\n    at Test.assert (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js:181:6)\n    at Server.localAssert (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js:131:12)\n    at Object.onceWrapper (node:events:641:28)\n    at Server.emit (node:events:527:28)\n    at emitCloseNT (node:net:1728:8)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":325935},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\mocha\\bin\\mocha","--exit","--recursive","--require","@babel/register","--timeout=5000","tests/**/*.js"],"cwd":"C:\\CFP_170\\NodeJs\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18911938,"external":28157820,"heapTotal":161492992,"heapUsed":129175032,"rss":196648960},"pid":8556,"uid":null,"version":"v16.15.1"},"stack":"AssertionError: expected 404 to equal 200\n    at Test.<anonymous> (C:\\CFP_170\\NodeJs\\FundooNotes\\tests\\integration\\/user.test.js:34:40)\n    at Test.assert (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js:181:6)\n    at Server.localAssert (C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js:131:12)\n    at Object.onceWrapper (node:events:641:28)\n    at Server.emit (node:events:527:28)\n    at emitCloseNT (node:net:1728:8)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-07-28T07:09:22.103Z","trace":[{"column":40,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\tests\\integration\\/user.test.js","function":null,"line":34,"method":null,"native":false},{"column":6,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js","function":"Test.assert","line":181,"method":"assert","native":false},{"column":12,"file":"C:\\CFP_170\\NodeJs\\FundooNotes\\node_modules\\supertest\\lib\\test.js","function":"Server.localAssert","line":131,"method":"localAssert","native":false},{"column":28,"file":"node:events","function":"Object.onceWrapper","line":641,"method":"onceWrapper","native":false},{"column":28,"file":"node:events","function":"Server.emit","line":527,"method":"emit","native":false},{"column":8,"file":"node:net","function":"emitCloseNT","line":1728,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":82,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T07:14:36.603Z"}
info: Connected to the database. {"timestamp":"2022-07-28T07:14:36.642Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T08:21:14.056Z"}
info: Connected to the database. {"timestamp":"2022-07-28T08:21:14.095Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T08:22:35.262Z"}
info: Connected to the database. {"timestamp":"2022-07-28T08:22:35.314Z"}
